const tabs=[...document.querySelectorAll('.tab')], forms={home:document.querySelector('#homeForm'),party:document.querySelector('#partyForm'),jewelry:document.querySelector('#jewelryForm')};let active='home',user=null;
const toast=m=>{const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
tabs.forEach(t=>t.onclick=()=>{active=t.dataset.panel;tabs.forEach(x=>x.classList.toggle('active',x===t));Object.entries(forms).forEach(([k,f])=>f.classList.toggle('hidden',k!==active));document.querySelector('#result').innerHTML='<div class="empty"><div class="empty-icon">✦</div><h3>Your plan takes shape here</h3><p>Choose a planner and enter a budget to see recommendations made around your needs.</p><div class="mini-note">Sign in to save your plans and revisit them later.</div></div>'});
async function api(url,opts={}){let r=await fetch(url,{...opts,headers:{...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opts.headers||{})}});let d=await r.json().catch(()=>({detail:'Something went wrong.'}));if(!r.ok)throw Error(d.detail||'Request failed');return d}
async function check(){try{const s=await api('/api/session-info');user=s.logged_in?s.email:null;document.querySelector('#authBtn').textContent=user?user.split('@')[0]+' · Sign out':'Sign in'}catch{}}
function authView(mode='login'){const c=document.querySelector('#authContent');let login=mode==='login';c.innerHTML=`<form class="auth-form" id="authForm"><h2>${login?'Welcome back':'Create your account'}</h2><p>${login?'Sign in to continue to your saved plans.':'Save recommendations and pick up where you left off.'}</p><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" minlength="8" required autocomplete="${login?'current-password':'new-password'}"></label><button class="button full">${login?'Sign in':'Create account'} →</button><button type="button" class="auth-switch">${login?'New here? Create an account':'Already have an account? Sign in'}</button></form>`;c.querySelector('.auth-switch').onclick=()=>authView(login?'register':'login');c.querySelector('form').onsubmit=async e=>{e.preventDefault();let fd=new FormData(e.target);try{await api('/api/'+(login?'login':'register'),{method:'POST',body:JSON.stringify(Object.fromEntries(fd))});document.querySelector('#authDialog').close();await check();toast('You’re signed in. Your next plan will be saved.')}catch(err){toast(err.message)}}}
document.querySelector('#authBtn').onclick=async()=>{if(user){try{await api('/api/logout',{method:'POST'});user=null;check();toast('Signed out')}catch{}}else{authView();document.querySelector('#authDialog').showModal()}};document.querySelector('#closeAuth').onclick=()=>document.querySelector('#authDialog').close();
function render(data){const r=document.querySelector('#result');r.innerHTML=`<div class="plan-card"><span class="ai-tag">✦ ${data.source==='gemini'?'AI PERSONALIZED':'POCKETSMART PLAN'}</span><h3>${esc(data.title)}</h3><p>${esc(data.summary)}</p>${data.items.map(i=>`<div class="rec"><div class="rec-top"><b>${esc(i.name)}</b><span class="price">${esc(i.currency||data.currency)} ${Number(i.estimated_price).toLocaleString('en-IN')}</span></div><small>${esc(i.reason)}</small><span class="platforms">Compare on: ${(i.platforms||[]).map(esc).join(' · ')}</span></div>`).join('')}<div class="total"><span>Estimated total</span><span>${esc(data.currency)} ${Number(data.total_estimate).toLocaleString('en-IN')}</span></div><div class="disclaimer">${esc(data.disclaimer||'Indicative estimates only.')}</div><div class="result-actions"><button onclick="window.print()">Print / Save PDF</button><button onclick="toast('Your plan is saved to history.')">Saved to history</button></div></div>`;r.scrollIntoView({behavior:'smooth',block:'nearest'})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
forms.home.onsubmit=async e=>{e.preventDefault();const f=e.target,d=new FormData(f);const rooms=[...f.elements.rooms.selectedOptions].map(x=>x.value);await submit('/api/generate-home',{budget:+d.get('budget'),currency:'INR',rooms,style:d.get('style'),priorities:d.get('priorities')})};
forms.party.onsubmit=async e=>{e.preventDefault();let d=new FormData(e.target);await submit('/api/generate-party',{budget:+d.get('budget'),currency:'INR',event_type:d.get('event_type'),guests:+d.get('guests'),city:d.get('city'),preferences:d.get('preferences')})};
forms.jewelry.onsubmit=async e=>{e.preventDefault();if(!user){authView();document.querySelector('#authDialog').showModal();toast('Sign in first to create and save a plan.');return}await submit('/api/generate-jewelry',new FormData(e.target),true)};
async function submit(url,body,isForm=false){if(!user){authView();document.querySelector('#authDialog').showModal();toast('Sign in first to create and save a plan.');return}const r=document.querySelector('#result');r.innerHTML='<div class="empty"><div class="empty-icon">◌</div><h3>Building your plan…</h3><p>Finding a thoughtful way to divide your budget.</p></div>';try{let d=await api(url,{method:'POST',body:isForm?body:JSON.stringify(body)});render(d);toast('Your plan is ready and saved.')}catch(err){r.innerHTML='<div class="empty"><h3>We couldn’t make that plan</h3><p>'+esc(err.message)+'</p></div>';if(err.message.includes('sign in')){authView();document.querySelector('#authDialog').showModal()}}}
check();